import {
  FiUsers,
  FiAward,
  FiCalendar,
  FiDollarSign,
  FiCreditCard,
  FiClock,
  FiUserPlus,
  FiCheckCircle,
  FiAlertCircle,
  FiStar,
  FiMail,
  FiMessageSquare,
  FiSettings,
} from "react-icons/fi";

export const getDashboardStats = () => [
  {
    icon: FiUsers,
    label: "Total Members",
    value: "2,847",
    change: "+12.5%",
    trend: "up",
    color: "blue",
  },
  {
    icon: FiAward,
    label: "Total Trainers",
    value: "24",
    change: "+2",
    trend: "up",
    color: "cyan",
  },
  {
    icon: FiCalendar,
    label: "Total Bookings",
    value: "1,432",
    change: "+18.2%",
    trend: "up",
    color: "emerald",
  },
  {
    icon: FiDollarSign,
    label: "Monthly Revenue",
    value: "$48,295",
    change: "+8.1%",
    trend: "up",
    color: "purple",
  },
  {
    icon: FiCreditCard,
    label: "Active Memberships",
    value: "1,892",
    change: "+5.3%",
    trend: "up",
    color: "amber",
  },
  {
    icon: FiClock,
    label: "Pending Requests",
    value: "37",
    change: "-4",
    trend: "down",
    color: "rose",
  },
];

export const getRecentActivities = () => [
  {
    id: 1,
    icon: FiCalendar,
    action: "New booking",
    detail: "HIIT Training booked by Sarah Wilson",
    time: "2 min ago",
    color: "blue",
  },
  {
    id: 2,
    icon: FiUserPlus,
    action: "New member",
    detail: "James Brown joined Premium plan",
    time: "15 min ago",
    color: "emerald",
  },
  {
    id: 3,
    icon: FiCheckCircle,
    action: "Booking completed",
    detail: "Yoga Session with Mike completed",
    time: "1 hour ago",
    color: "cyan",
  },
  {
    id: 4,
    icon: FiMessageSquare,
    action: "New testimonial",
    detail: "Emily left a 5-star review",
    time: "2 hours ago",
    color: "purple",
  },
  {
    id: 5,
    icon: FiSettings,
    action: "Settings updated",
    detail: "Hero section content refreshed",
    time: "3 hours ago",
    color: "amber",
  },
  {
    id: 6,
    icon: FiAlertCircle,
    action: "Cancellation",
    detail: "Mike cancelled Strength Training",
    time: "5 hours ago",
    color: "rose",
  },
];

export const getUpcomingBookings = () => [
  {
    id: 1,
    member: "Sarah Wilson",
    trainer: "Alex Turner",
    session: "HIIT Training",
    date: "Today",
    time: "2:00 PM",
    status: "confirmed",
    avatar: "SW",
  },
  {
    id: 2,
    member: "James Brown",
    trainer: "Lisa Chen",
    session: "Yoga Flow",
    date: "Today",
    time: "4:30 PM",
    status: "confirmed",
    avatar: "JB",
  },
  {
    id: 3,
    member: "Emily Davis",
    trainer: "Mike Ross",
    session: "Strength Training",
    date: "Tomorrow",
    time: "9:00 AM",
    status: "pending",
    avatar: "ED",
  },
  {
    id: 4,
    member: "Chris Lee",
    trainer: "Sarah Kim",
    session: "Pilates",
    date: "Tomorrow",
    time: "11:00 AM",
    status: "confirmed",
    avatar: "CL",
  },
  {
    id: 5,
    member: "Anna Martinez",
    trainer: "Alex Turner",
    session: "CrossFit",
    date: "Jul 14",
    time: "7:00 AM",
    status: "pending",
    avatar: "AM",
  },
];

export const getRecentMembers = () => [
  {
    id: 1,
    name: "James Brown",
    email: "james@example.com",
    plan: "Premium",
    joined: "2 hours ago",
    avatar: "JB",
    status: "active",
  },
  {
    id: 2,
    name: "Sophia Garcia",
    email: "sophia@example.com",
    plan: "Standard",
    joined: "5 hours ago",
    avatar: "SG",
    status: "active",
  },
  {
    id: 3,
    name: "Liam Johnson",
    email: "liam@example.com",
    plan: "Basic",
    joined: "1 day ago",
    avatar: "LJ",
    status: "active",
  },
  {
    id: 4,
    name: "Olivia Chen",
    email: "olivia@example.com",
    plan: "VIP Elite",
    joined: "2 days ago",
    avatar: "OC",
    status: "active",
  },
];

export const getRevenueData = () => ({
  months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
  revenue: [32000, 35000, 38000, 42000, 40000, 45000, 48295, 0, 0, 0, 0, 0],
  bookings: [180, 195, 210, 225, 240, 235, 248, 0, 0, 0, 0, 0],
  memberships: [120, 135, 142, 155, 160, 170, 185, 0, 0, 0, 0, 0],
});

export const getNotifications = () => [
  {
    id: 1,
    icon: FiCalendar,
    title: "New booking received",
    message: "Sarah Wilson booked HIIT Training for today",
    time: "2 min ago",
    read: false,
    color: "blue",
  },
  {
    id: 2,
    icon: FiUserPlus,
    title: "New member joined",
    message: "James Brown upgraded to Premium plan",
    time: "15 min ago",
    read: false,
    color: "emerald",
  },
  {
    id: 3,
    icon: FiStar,
    title: "New review",
    message: "Emily left a 5-star testimonial",
    time: "1 hour ago",
    read: true,
    color: "amber",
  },
  {
    id: 4,
    icon: FiMail,
    title: "Contact form submission",
    message: "New inquiry from the contact page",
    time: "3 hours ago",
    read: true,
    color: "purple",
  },
  {
    id: 5,
    icon: FiAlertCircle,
    title: "Booking cancelled",
    message: "Mike cancelled Strength Training session",
    time: "5 hours ago",
    read: true,
    color: "rose",
  },
];

export const getQuickActions = () => [
  {
    id: "add-trainer",
    label: "Add Trainer",
    icon: FiAward,
    color: "cyan",
    href: "/dashboard/trainers",
  },
  {
    id: "add-service",
    label: "Add Service",
    icon: FiCheckCircle,
    color: "emerald",
    href: "/dashboard/services",
  },
  {
    id: "view-bookings",
    label: "View Bookings",
    icon: FiCalendar,
    color: "blue",
    href: "/dashboard",
  },
  {
    id: "update-hero",
    label: "Update Hero",
    icon: FiStar,
    color: "amber",
    href: "/dashboard/hero",
  },
];
