export const getGalleryImages = () => [
  {
    id: 1,
    title: "Modern Gym Interior",
    category: "Facility",
    description: "State-of-the-art gym with premium equipment and spacious workout areas.",
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&h=600&fit=crop&auto=format&q=80",
    featured: true,
    status: "active",
    updatedAt: "2 hours ago",
  },
  {
    id: 2,
    title: "Group Yoga Session",
    category: "Classes",
    description: "Morning yoga classes with certified instructors in our dedicated studio.",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop&auto=format&q=80",
    featured: false,
    status: "active",
    updatedAt: "1 day ago",
  },
  {
    id: 3,
    title: "Weight Lifting Area",
    category: "Strength",
    description: "Comprehensive free weights section with Olympic platforms and power racks.",
    image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&h=600&fit=crop&auto=format&q=80",
    featured: true,
    status: "active",
    updatedAt: "3 days ago",
  },
  {
    id: 4,
    title: "CrossFit Training Zone",
    category: "CrossFit",
    description: "Dedicated CrossFit box with rig, rowers, and functional equipment.",
    image: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800&h=600&fit=crop&auto=format&q=80",
    featured: false,
    status: "active",
    updatedAt: "1 week ago",
  },
  {
    id: 5,
    title: "Cardio Deck",
    category: "Cardio",
    description: "Premium cardio floor with treadmills, ellipticals, and stunning city views.",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&h=600&fit=crop&auto=format&q=80",
    featured: false,
    status: "active",
    updatedAt: "1 week ago",
  },
  {
    id: 6,
    title: "Recovery Lounge",
    category: "Wellness",
    description: "Post-workout recovery area with massage chairs, cold plunge, and sauna.",
    image: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=800&h=1000&fit=crop&auto=format&q=80",
    featured: true,
    status: "active",
    updatedAt: "2 weeks ago",
  },
  {
    id: 7,
    title: "Personal Training Session",
    category: "Training",
    description: "One-on-one personal training with customized workout programs.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop&auto=format&q=80",
    featured: false,
    status: "active",
    updatedAt: "3 weeks ago",
  },
  {
    id: 8,
    title: "Premium Equipment",
    category: "Equipment",
    description: "Latest Technogym and Hammer Strength equipment throughout the facility.",
    image: "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=800&h=1000&fit=crop&auto=format&q=80",
    featured: false,
    status: "draft",
    updatedAt: "1 month ago",
  },
  {
    id: 9,
    title: "Swimming Pool",
    category: "Facility",
    description: "Olympic-sized indoor swimming pool with dedicated lap lanes and spa area.",
    image: "https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=800&h=600&fit=crop&auto=format&q=80",
    featured: false,
    status: "active",
    updatedAt: "1 month ago",
  },
  {
    id: 10,
    title: "Climbing Wall",
    category: "Training",
    description: "Indoor climbing wall with multiple difficulty levels for all skill ranges.",
    image: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&h=600&fit=crop&auto=format&q=80",
    featured: false,
    status: "draft",
    updatedAt: "1 month ago",
  },
];

export const getGalleryStats = (images) => ({
  total: images.length,
  featured: images.filter((i) => i.featured).length,
  albums: [...new Set(images.map((i) => i.category))].length,
  storage: "2.4 GB",
});

export const getGalleryCategories = () => [
  { value: "Facility", label: "Facility" },
  { value: "Classes", label: "Classes" },
  { value: "Strength", label: "Strength" },
  { value: "CrossFit", label: "CrossFit" },
  { value: "Cardio", label: "Cardio" },
  { value: "Wellness", label: "Wellness" },
  { value: "Training", label: "Training" },
  { value: "Equipment", label: "Equipment" },
];
