export const getHeroSections = () => [
  {
    id: 1,
    title: "Train Smarter. Live Stronger.",
    subtitle: "Transform Your Body",
    description:
      "Book professional fitness classes, discover expert trainers, and start your healthy lifestyle today.",
    buttonText: "Book Now",
    buttonLink: "/booking",
    secondaryText: "Learn More",
    secondaryLink: "/about",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
    status: "active",
    members: "2,847",
    trainers: "24",
    classes: "50+",
    updatedAt: "2 hours ago",
  },
  {
    id: 2,
    title: "Elite Training Experience",
    subtitle: "Premium Fitness",
    description:
      "Access world-class trainers and cutting-edge equipment for your ultimate fitness transformation.",
    buttonText: "Get Started",
    buttonLink: "/membership",
    secondaryText: "View Plans",
    secondaryLink: "/membership",
    image: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800",
    status: "active",
    members: "2,847",
    trainers: "24",
    classes: "50+",
    updatedAt: "1 day ago",
  },
  {
    id: 3,
    title: "Summer Fitness Challenge",
    subtitle: "Limited Time",
    description:
      "Join our exclusive summer challenge and transform your body in 12 weeks with expert guidance.",
    buttonText: "Join Challenge",
    buttonLink: "/booking",
    secondaryText: "Details",
    secondaryLink: "/about",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800",
    status: "draft",
    members: "2,847",
    trainers: "24",
    classes: "50+",
    updatedAt: "3 days ago",
  },
  {
    id: 4,
    title: "Group Classes Now Live",
    subtitle: "New Feature",
    description:
      "Explore our new range of group fitness classes from yoga to high-intensity interval training.",
    buttonText: "Explore Classes",
    buttonLink: "/services",
    secondaryText: "Schedule",
    secondaryLink: "/booking",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800",
    status: "draft",
    members: "2,847",
    trainers: "24",
    classes: "50+",
    updatedAt: "1 week ago",
  },
];

export const getHeroStats = (sections) => ({
  total: sections.length,
  active: sections.filter((s) => s.status === "active").length,
  draft: sections.filter((s) => s.status === "draft").length,
});
