export const getNotifications = () => [
  {
    id: 1,
    type: "booking",
    title: "New Booking Confirmed",
    message: "Sarah Johnson booked Personal Training with Alex Turner for tomorrow at 10:00 AM.",
    time: "2 minutes ago",
    read: false,
    icon: "booking",
  },
  {
    id: 2,
    type: "membership",
    title: "Membership Upgraded",
    message: "Michael Chen upgraded from Basic Fit to Elite Pro plan.",
    time: "15 minutes ago",
    read: false,
    icon: "membership",
  },
  {
    id: 3,
    type: "message",
    title: "New Contact Message",
    message: "Jessica Williams sent a message about group class schedules.",
    time: "1 hour ago",
    read: false,
    icon: "message",
  },
  {
    id: 4,
    type: "system",
    title: "System Update Complete",
    message: "Platform v2.4.1 has been successfully deployed. All services are running normally.",
    time: "2 hours ago",
    read: true,
    icon: "system",
  },
  {
    id: 5,
    type: "booking",
    title: "Booking Cancelled",
    message: "Robert Davis cancelled his CrossFit session scheduled for Friday.",
    time: "3 hours ago",
    read: true,
    icon: "booking",
  },
  {
    id: 6,
    type: "membership",
    title: "Membership Expiring",
    message: "Emily Brown's Premium Active plan expires in 3 days. Consider sending a renewal reminder.",
    time: "5 hours ago",
    read: false,
    icon: "membership",
  },
  {
    id: 7,
    type: "system",
    title: "Backup Completed",
    message: "Daily database backup completed successfully. Next backup scheduled for tomorrow.",
    time: "6 hours ago",
    read: true,
    icon: "system",
  },
  {
    id: 8,
    type: "message",
    title: "New Review Received",
    message: "David Thompson left a 5-star review for the Yoga Flow class.",
    time: "8 hours ago",
    read: true,
    icon: "message",
  },
  {
    id: 9,
    type: "booking",
    title: "Recurring Booking Reminder",
    message: "12 recurring bookings are scheduled for next week. Ensure trainer availability.",
    time: "1 day ago",
    read: true,
    icon: "booking",
  },
  {
    id: 10,
    type: "system",
    title: "Storage Warning",
    message: "Gallery storage usage has reached 75%. Consider optimizing image sizes.",
    time: "1 day ago",
    read: true,
    icon: "system",
  },
  {
    id: 11,
    type: "membership",
    title: "New Registration",
    message: "Amanda Martinez signed up for the Student Saver plan.",
    time: "2 days ago",
    read: true,
    icon: "membership",
  },
  {
    id: 12,
    type: "message",
    title: "Support Ticket",
    message: "Thomas Anderson reported an issue with the booking calendar display.",
    time: "2 days ago",
    read: true,
    icon: "message",
  },
];

export const getNotificationStats = (notifications) => ({
  total: notifications.length,
  unread: notifications.filter((n) => !n.read).length,
  booking: notifications.filter((n) => n.type === "booking").length,
  membership: notifications.filter((n) => n.type === "membership").length,
  message: notifications.filter((n) => n.type === "message").length,
  system: notifications.filter((n) => n.type === "system").length,
});
