export const getServices = () => [
  {
    id: 1,
    name: "Personal Training",
    category: "Training",
    price: "$49",
    duration: "60 min",
    trainer: "Alex Turner",
    description: "One-on-one sessions with certified trainers tailored to your goals.",
    benefits: "Customized plan, Progress tracking, Nutrition advice",
    featured: true,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
    status: "active",
    updatedAt: "2 hours ago",
  },
  {
    id: 2,
    name: "Strength Training",
    category: "Training",
    price: "$39",
    duration: "45 min",
    trainer: "Mike Ross",
    description: "Build muscle and increase endurance with progressive overload.",
    benefits: "Muscle building, Bone density, Metabolism boost",
    featured: true,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
    status: "active",
    updatedAt: "1 day ago",
  },
  {
    id: 3,
    name: "Yoga Flow",
    category: "Wellness",
    price: "$29",
    duration: "60 min",
    trainer: "Lisa Chen",
    description: "Restore balance through mindful movement and breathwork.",
    benefits: "Flexibility, Stress relief, Mental clarity",
    featured: false,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800",
    status: "active",
    updatedAt: "3 days ago",
  },
  {
    id: 4,
    name: "HIIT Cardio",
    category: "Cardio",
    price: "$35",
    duration: "30 min",
    trainer: "Sarah Kim",
    description: "High-intensity interval training for maximum calorie burn.",
    benefits: "Fat burning, Cardiovascular health, Time efficient",
    featured: true,
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800",
    status: "active",
    updatedAt: "1 week ago",
  },
  {
    id: 5,
    name: "CrossFit",
    category: "Training",
    price: "$45",
    duration: "50 min",
    trainer: "Alex Turner",
    description: "Intense functional workouts for total body fitness.",
    benefits: "Full body workout, Community, Functional strength",
    featured: false,
    image: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800",
    status: "active",
    updatedAt: "2 weeks ago",
  },
  {
    id: 6,
    name: "Nutrition Coaching",
    category: "Wellness",
    price: "$59",
    duration: "45 min",
    trainer: "Dr. Amy Patel",
    description: "Expert dietary guidance tailored to your fitness goals.",
    benefits: "Meal planning, Supplements, Body composition",
    featured: false,
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800",
    status: "active",
    updatedAt: "3 weeks ago",
  },
  {
    id: 7,
    name: "Pilates Core",
    category: "Wellness",
    price: "$32",
    duration: "45 min",
    trainer: "Lisa Chen",
    description: "Core-strengthening exercises for posture and flexibility.",
    benefits: "Core strength, Posture, Injury prevention",
    featured: false,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800",
    status: "draft",
    updatedAt: "1 month ago",
  },
  {
    id: 8,
    name: "Boxing Fitness",
    category: "Cardio",
    price: "$42",
    duration: "45 min",
    trainer: "Mike Ross",
    description: "Boxing-inspired workout for cardio and coordination.",
    benefits: "Cardio, Coordination, Stress relief",
    featured: false,
    image: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800",
    status: "draft",
    updatedAt: "1 month ago",
  },
];

export const getServiceStats = (services) => ({
  total: services.length,
  active: services.filter((s) => s.status === "active").length,
  featured: services.filter((s) => s.featured).length,
  categories: [...new Set(services.map((s) => s.category))].length,
});

export const getServiceCategories = () => [
  { value: "Training", label: "Training" },
  { value: "Wellness", label: "Wellness" },
  { value: "Cardio", label: "Cardio" },
];
