export const getTestimonials = () => [
  {
    id: 1,
    customerName: "Sarah Johnson",
    customerPhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&auto=format&q=80",
    profession: "Marketing Director",
    rating: 5,
    review: "FitBookPro completely transformed my fitness journey. The trainers are world-class and the community keeps me motivated. Lost 25 lbs in 3 months!",
    membership: "Premium Active",
    featured: true,
    status: "active",
    updatedAt: "2 hours ago",
  },
  {
    id: 2,
    customerName: "Michael Chen",
    customerPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&auto=format&q=80",
    profession: "Software Engineer",
    rating: 5,
    review: "Best fitness platform I've ever used. Easy to book classes, track progress, and the personal training sessions are exceptional. Highly recommended!",
    membership: "Elite Pro",
    featured: true,
    status: "active",
    updatedAt: "1 day ago",
  },
  {
    id: 3,
    customerName: "Jessica Williams",
    customerPhoto: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&auto=format&q=80",
    profession: "Yoga Instructor",
    rating: 5,
    review: "The variety of classes and the quality of instruction is outstanding. I love the yoga and pilates programs. The community atmosphere is amazing!",
    membership: "Premium Active",
    featured: false,
    status: "active",
    updatedAt: "3 days ago",
  },
  {
    id: 4,
    customerName: "Robert Davis",
    customerPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&auto=format&q=80",
    profession: "Business Owner",
    rating: 4,
    review: "Great variety of classes and the community keeps me motivated every day. The nutrition coaching helped me completely change my lifestyle.",
    membership: "Elite Pro",
    featured: false,
    status: "active",
    updatedAt: "1 week ago",
  },
  {
    id: 5,
    customerName: "Amanda Martinez",
    customerPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&auto=format&q=80",
    profession: "Healthcare Professional",
    rating: 5,
    review: "The rehabilitation program here is top-notch. After my knee surgery, the trainers helped me recover stronger than before. Forever grateful!",
    membership: "Premium Active",
    featured: true,
    status: "active",
    updatedAt: "2 weeks ago",
  },
  {
    id: 6,
    customerName: "David Thompson",
    customerPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&auto=format&q=80",
    profession: "Personal Trainer",
    rating: 4,
    review: "As a fellow trainer, I can appreciate the quality of equipment and facilities. The CrossFit zone is phenomenal and the coaches are elite.",
    membership: "Basic Fit",
    featured: false,
    status: "active",
    updatedAt: "3 weeks ago",
  },
  {
    id: 7,
    customerName: "Emily Parker",
    customerPhoto: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&auto=format&q=80",
    profession: "College Student",
    rating: 5,
    review: "The student plan is perfect! Affordable and I get access to everything I need. Group classes are so much fun and the trainers are supportive.",
    membership: "Student Saver",
    featured: false,
    status: "active",
    updatedAt: "1 month ago",
  },
  {
    id: 8,
    customerName: "Thomas Anderson",
    customerPhoto: "",
    profession: "Accountant",
    rating: 3,
    review: "Good facilities and decent classes. The booking system could be improved but overall a solid gym experience. Parking could be better.",
    membership: "Basic Fit",
    featured: false,
    status: "draft",
    updatedAt: "1 month ago",
  },
];

export const getTestimonialStats = (testimonials) => ({
  total: testimonials.length,
  avgRating:
    testimonials.length > 0
      ? (
          testimonials.reduce((sum, t) => sum + t.rating, 0) /
          testimonials.length
        ).toFixed(1)
      : "0.0",
  featured: testimonials.filter((t) => t.featured).length,
  pending: testimonials.filter((t) => t.status === "draft").length,
});
