export const getTrainers = () => [
  {
    id: 1,
    name: "Alex Turner",
    email: "alex@fitbookpro.com",
    phone: "+1 (555) 123-4567",
    specialization: "Strength Training",
    experience: "12 years",
    designation: "Head Strength Coach",
    workingDays: "Mon, Tue, Wed, Thu, Fri",
    workingHours: "6:00 AM - 2:00 PM",
    hours: "6:00 AM - 2:00 PM",
    bio: "Certified strength and conditioning specialist with over a decade of experience transforming clients' fitness levels.",
    certificates: "CSCS, NSCA-CPT, USAW Level 2",
    facebook: "https://facebook.com/alexturner",
    instagram: "https://instagram.com/alexturner",
    linkedin: "https://linkedin.com/in/alexturner",
    social: { instagram: "https://instagram.com/alexturner", twitter: "https://twitter.com/alexturner", linkedin: "https://linkedin.com/in/alexturner" },
    image: "https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=400&h=400&fit=crop&auto=format&q=80",
    status: "active",
    rating: 4.9,
    reviews: 128,
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    skills: ["Powerlifting", "Olympic Lifting", "Hypertrophy", "Functional Training", "Nutrition Planning"],
    programs: ["12-Week Strength Foundation", "Athletic Performance Boost", "Body Recomposition", "Competition Prep"],
    certificateObjects: [
      { name: "CSCS", year: "2015" },
      { name: "NSCA-CPT", year: "2014" },
      { name: "USAW Level 2", year: "2017" },
    ],
    achievements: ["State Powerlifting Champion 2018", "500+ Clients Trained", "Featured in Muscle & Fitness Magazine"],
    updatedAt: "2 hours ago",
  },
  {
    id: 2,
    name: "Sarah Williams",
    email: "sarah@fitbookpro.com",
    phone: "+1 (555) 234-5678",
    specialization: "Yoga & Pilates",
    experience: "8 years",
    designation: "Senior Yoga Instructor",
    workingDays: "Mon, Wed, Fri, Sat",
    workingHours: "7:00 AM - 3:00 PM",
    hours: "7:00 AM - 3:00 PM",
    bio: "Registered yoga teacher and Pilates instructor passionate about holistic wellness and mindful movement practices.",
    certificates: "RYT-500, STOTT Pilates, ACE Group Fitness",
    facebook: "https://facebook.com/sarahwilliams",
    instagram: "https://instagram.com/sarahwilliams",
    linkedin: "https://linkedin.com/in/sarahwilliams",
    social: { instagram: "https://instagram.com/sarahwilliams", twitter: "https://twitter.com/sarahwilliams", linkedin: "https://linkedin.com/in/sarahwilliams" },
    image: "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=400&fit=crop&auto=format&q=80",
    status: "active",
    rating: 4.8,
    reviews: 96,
    availableDays: ["Mon", "Wed", "Fri", "Sat"],
    skills: ["Vinyasa Flow", "Hatha Yoga", "Mat Pilates", "Reformer Pilates", "Meditation"],
    programs: ["Morning Flow Series", "Pilates Core Reset", "Stress Relief Yoga", "Prenatal Yoga"],
    certificateObjects: [
      { name: "RYT-500", year: "2017" },
      { name: "STOTT Pilates", year: "2018" },
      { name: "ACE Group Fitness", year: "2016" },
    ],
    achievements: ["Led 200+ Workshops", "Wellness Retreat Leader", "Published in Yoga Journal"],
    updatedAt: "1 day ago",
  },
  {
    id: 3,
    name: "Mike Ross",
    email: "mike@fitbookpro.com",
    phone: "+1 (555) 345-6789",
    specialization: "CrossFit",
    experience: "10 years",
    designation: "Head CrossFit Coach",
    workingDays: "Mon, Tue, Thu, Fri, Sat",
    workingHours: "5:00 AM - 1:00 PM",
    hours: "5:00 AM - 1:00 PM",
    bio: "CrossFit Level 3 trainer and former competitive athlete dedicated to pushing boundaries and building resilient athletes.",
    certificates: "CF-L3, Kettlebell Athletics, Precision Nutrition L1",
    facebook: "https://facebook.com/mikeross",
    instagram: "https://instagram.com/mikeross",
    linkedin: "https://linkedin.com/in/mikeross",
    social: { instagram: "https://instagram.com/mikeross", twitter: "https://twitter.com/mikeross", linkedin: "https://linkedin.com/in/mikeross" },
    image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&h=400&fit=crop&auto=format&q=80",
    status: "active",
    rating: 4.7,
    reviews: 112,
    availableDays: ["Mon", "Tue", "Thu", "Fri", "Sat"],
    skills: ["CrossFit L3", "Olympic Lifting", "Gymnastics", "Endurance", "Mobility"],
    programs: ["CrossFit Fundamentals", "Competition WOD", "Endurance Builder", "Mobility Recovery"],
    certificateObjects: [
      { name: "CF-L3", year: "2016" },
      { name: "Kettlebell Athletics", year: "2017" },
      { name: "Precision Nutrition L1", year: "2019" },
    ],
    achievements: ["Regional CrossFit Competitor", "Opened 3 CrossFit Affiliates", "Coach to 50+ Competition Athletes"],
    updatedAt: "3 days ago",
  },
  {
    id: 4,
    name: "Lisa Chen",
    email: "lisa@fitbookpro.com",
    phone: "+1 (555) 456-7890",
    specialization: "HIIT & Cardio",
    experience: "6 years",
    designation: "Cardio & HIIT Specialist",
    workingDays: "Tue, Wed, Thu, Sat",
    workingHours: "8:00 AM - 4:00 PM",
    hours: "8:00 AM - 4:00 PM",
    bio: "High-energy fitness coach specializing in cardiovascular endurance and metabolic conditioning programs.",
    certificates: "ACE-CPT, TRX Qualified, Les Mills BPM",
    facebook: "https://facebook.com/lisachen",
    instagram: "https://instagram.com/lisachen",
    linkedin: "https://linkedin.com/in/lisachen",
    social: { instagram: "https://instagram.com/lisachen", twitter: "https://twitter.com/lisachen", linkedin: "https://linkedin.com/in/lisachen" },
    image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=400&h=400&fit=crop&auto=format&q=80",
    status: "active",
    rating: 4.6,
    reviews: 84,
    availableDays: ["Tue", "Wed", "Thu", "Sat"],
    skills: ["HIIT Training", "Sprint Intervals", "Tabata", "Metabolic Conditioning", "Group Fitness"],
    programs: ["30-Minute Burn", "Tabata Thunder", "Cardio Kickboxing", "Metabolic Blast"],
    certificateObjects: [
      { name: "ACE-CPT", year: "2019" },
      { name: "TRX Qualified", year: "2020" },
      { name: "Les Mills BPM", year: "2020" },
    ],
    achievements: ["Top Rated Cardio Coach 2024", "Led 500+ HIIT Sessions", "Fitness YouTube Channel 10K Subs"],
    updatedAt: "1 week ago",
  },
  {
    id: 5,
    name: "David Kim",
    email: "david@fitbookpro.com",
    phone: "+1 (555) 567-8901",
    specialization: "Nutrition & Wellness",
    experience: "9 years",
    designation: "Head Nutritionist",
    workingDays: "Mon, Tue, Wed, Thu",
    workingHours: "9:00 AM - 5:00 PM",
    hours: "9:00 AM - 5:00 PM",
    bio: "Certified nutritionist and wellness coach helping clients achieve optimal health through science-backed dietary strategies.",
    certificates: "CISSN, Precision Nutrition L2, ISSN Diploma",
    facebook: "https://facebook.com/davidkim",
    instagram: "https://instagram.com/davidkim",
    linkedin: "https://linkedin.com/in/davidkim",
    social: { instagram: "https://instagram.com/davidkim", twitter: "https://twitter.com/davidkim", linkedin: "https://linkedin.com/in/davidkim" },
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&auto=format&q=80",
    status: "active",
    rating: 4.9,
    reviews: 145,
    availableDays: ["Mon", "Tue", "Wed", "Thu"],
    skills: ["Sports Nutrition", "Meal Planning", "Supplement Guidance", "Body Composition", "Macro Tracking"],
    programs: ["12-Week Nutrition Reset", "Athlete Fuel Plan", "Weight Loss Protocol", "Muscle Gain Nutrition"],
    certificateObjects: [
      { name: "CISSN", year: "2016" },
      { name: "Precision Nutrition L2", year: "2018" },
      { name: "ISSN Diploma", year: "2017" },
    ],
    achievements: ["Published Nutrition Research", "NBA Team Nutrition Consultant", "500+ Transformations"],
    updatedAt: "2 weeks ago",
  },
  {
    id: 6,
    name: "Emily Brown",
    email: "emily@fitbookpro.com",
    phone: "+1 (555) 678-9012",
    specialization: "Boxing & MMA",
    experience: "5 years",
    designation: "Boxing & MMA Coach",
    workingDays: "Mon, Wed, Fri",
    workingHours: "10:00 AM - 6:00 PM",
    hours: "10:00 AM - 6:00 PM",
    bio: "Former amateur boxing champion turned fitness coach, combining combat sports with functional fitness training.",
    certificates: "USA Boxing Coach, ACE-CPT, First Aid/CPR",
    facebook: "https://facebook.com/emilybrown",
    instagram: "https://instagram.com/emilybrown",
    linkedin: "https://linkedin.com/in/emilybrown",
    social: { instagram: "https://instagram.com/emilybrown", twitter: "https://twitter.com/emilybrown", linkedin: "https://linkedin.com/in/emilybrown" },
    image: "https://images.unsplash.com/photo-1548690312-e3b507d8c110?w=400&h=400&fit=crop&auto=format&q=80",
    status: "inactive",
    rating: 4.5,
    reviews: 67,
    availableDays: ["Mon", "Wed", "Fri"],
    skills: ["Boxing", "MMA Conditioning", "Self-Defense", "Footwork Drills", "Heavy Bag Training"],
    programs: ["Boxing Fundamentals", "MMA Conditioning", "Fight Fitness", "Cardio Kickboxing"],
    certificateObjects: [
      { name: "USA Boxing Coach", year: "2020" },
      { name: "ACE-CPT", year: "2019" },
      { name: "First Aid/CPR", year: "2024" },
    ],
    achievements: ["Amateur Boxing Champion 2017", "Coached 2 Pro Fighters", "Women in Sports Award"],
    updatedAt: "1 month ago",
  },
  {
    id: 7,
    name: "James Wilson",
    email: "james@fitbookpro.com",
    phone: "+1 (555) 789-0123",
    specialization: "Rehabilitation",
    experience: "15 years",
    designation: "Rehabilitation Director",
    workingDays: "Mon, Tue, Wed, Thu, Fri",
    workingHours: "8:00 AM - 4:00 PM",
    hours: "8:00 AM - 4:00 PM",
    bio: "Physical therapist and corrective exercise specialist with 15 years of experience in injury prevention and rehabilitation.",
    certificates: "DPT, NASM-CES, FMS Level 2",
    facebook: "https://facebook.com/jameswilson",
    instagram: "https://instagram.com/jameswilson",
    linkedin: "https://linkedin.com/in/jameswilson",
    social: { instagram: "https://instagram.com/jameswilson", twitter: "https://twitter.com/jameswilson", linkedin: "https://linkedin.com/in/jameswilson" },
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&auto=format&q=80",
    status: "active",
    rating: 4.8,
    reviews: 162,
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    skills: ["Sports Rehabilitation", "Corrective Exercise", "Manual Therapy", "Dry Needling", "FMS Screening"],
    programs: ["Post-Surgery Recovery", "Injury Prevention Screen", "Corrective Exercise Plan", "Return to Sport Protocol"],
    certificateObjects: [
      { name: "DPT", year: "2010" },
      { name: "NASM-CES", year: "2013" },
      { name: "FMS Level 2", year: "2015" },
    ],
    achievements: ["Treated 1000+ Athletes", "Published Rehabilitation Research", "Olympic Team Consultant"],
    updatedAt: "3 weeks ago",
  },
];

export const getTrainerById = (id) => {
  const numId = Number(id);
  return getTrainers().find((t) => t.id === numId) || null;
};

export const getTrainerStats = (trainers) => ({
  total: trainers.length,
  active: trainers.filter((t) => t.status === "active").length,
  specializations: [...new Set(trainers.map((t) => t.specialization))].length,
  avgRating:
    trainers.length > 0
      ? (
          trainers.reduce((sum, t) => sum + t.rating, 0) / trainers.length
        ).toFixed(1)
      : "0.0",
});

export const getSpecializations = () => [
  { value: "Strength Training", label: "Strength Training" },
  { value: "Yoga & Pilates", label: "Yoga & Pilates" },
  { value: "CrossFit", label: "CrossFit" },
  { value: "HIIT & Cardio", label: "HIIT & Cardio" },
  { value: "Nutrition & Wellness", label: "Nutrition & Wellness" },
  { value: "Boxing & MMA", label: "Boxing & MMA" },
  { value: "Rehabilitation", label: "Rehabilitation" },
];
